# import! gnuplot = gnuplot%exe{gnuplot}
# info $path($gnuplot)

./: lib{lyrahgames-gnuplot}: hxx{** -version} hxx{version}
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
}
cxx.poptions =+ "-I$out_root" "-I$src_root"

hxx{version}: in{version} $src_root/manifest
{
  dist = true
  clean = ($src_root != $out_root)
}

hxx{**}:
{
  install = include/lyrahgames/gnuplot/
  install.subdirs = true
}
